config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'sessions/create'
  post 'sessions/create'

  delete 'sessions/destroy'

  get 'users/show'

  get 'users/new'
  post 'users/new'

  get 'users/edit'

  post 'users/create'

  get 'users/destroy'

  get 'users/update'

  resources :beers do
    resources :reviews
  end

  resources :users

  root 'dashboards#index'

end

app/models/beer.rb
class Beer < ActiveRecord::Base
  has_many :reviews
  validates :name, :brewer, :ounce, :ounce, presence: true

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :beer
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private def authenticate
    if session[:user_id].nil?
      redirect_to authenticate_login_path, notice: "Nice try, log in first."
    end
  end
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController

  def index
    @beers = Beer.all
  end

  def show
    @beer = Beer.find(params[:id])
  end

  def new
    @beer = Beer.new
  end

  def edit
    @beer = Beer.find(params[:id])
  end

  def create
    @beer = Beer.new(beer_params)

    if @beer.save
      redirect_to @beer
    else
      render 'new'
    end
  end

  def update
    @beer = Beer.find(params[:id])

    if @beer.update(beer_params)
      redirect_to @beer
    else
      render 'edit'
    end
  end

  def destroy
    @beer = Beer.find(params[:id])
    @beer.destroy

    redirect_to beers_path
  end

  private
    def beer_params
      params.require(:beer).permit(:name, :brewer, :price, :ounce, :calorie, :rating)
    end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @beer = Beer.find(params[:beer_id])
    @review = @beer.reviews.create(review_params)
    redirect_to beer_path(@beer)
  end

  def destroy
    @beer = Beer.find(params[:beer_id])
    @review = @beer.reviews.find(params[:id])
    @review.destroy
    redirect_to beer_path(@beer)
  end

  private
    def review_params
      params.require(:review).permit(:commenter, :body)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    if request.post?
    user = User.find_by(email: params[:email])
      if user && user.authenticate(params[:password])
        redirect_to beers_path, notice: "You're in."
      else
        flash[:notice] = "Well, that didn't work."
      end
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to sessions_create_path, notice: "You'll be back. Probably."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to beers_path, notice: "You exist now."
    else
      redirect_to users_create_path, notice: "Nah, log in first."
    end
  end

  def destroy
    if @user.destroy
      redirect_to users_url, notice: 'User was successfully destroyed.'
    end
  end

  def update
  end

  private
    def user_params
      params.require(:user).permit(:id, :password, :token, :email)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/beers/_form.html.erb
<center>

<%= form_for @beer do |f| %>

  <% if @beer.errors.any? %>
      <div id="error_explanation">
        <p>
          <%= pluralize(@beer.errors.count, "error") %> prohibited
          this article from being saved:
        </p>
          <% @beer.errors.full_messages.each do |msg| %>
            <li><center><%= msg %></li>
          <% end %>
      </div>
    <% end %>

  <p>
    <strong><%= f.label :name %><br></strong>
    <%= f.text_field :name %>
  </p>

  <p>
    <strong><%= f.label :brewer %><br></strong>
    <%= f.text_field :brewer %>
  </p>

  <p>
    <strong><%= f.label :price %><br></strong>
    <%= f.number_field :price %>
  </p>

  <p>
    <strong><%= f.label :ounce %><br></strong>
    <%= f.number_field :ounce %>
  </p>

  <p>
    <strong><%= f.label :calorie %><br></strong>
    <%= f.number_field :calorie %>
  </p>

  <center><p>
    <%= f.label :rating %><br>
    <%= f.select :rating, [[0], [1], [2], [3], [4], [5]] %>
  </p></center>
  <!-- <p><strong>Rating</strong>
  <%= f.select :rating, options_for_select([['opt1'], ['opt2'], ['opt3'], ['opt4'], ['opt5']]) %>
  </p> -->

  <p>
    <%= f.submit class: 'sub-btn'%>
  </p>
<% end %>
</center>

app/views/beers/edit.html.erb
<center>

<h1> Edit the beer </h1>

<%= render 'form' %>

<%= link_to "BACK", beers_path %> | <%= link_to "LOG OUT", sessions_destroy_path %>

</center>

app/views/beers/index.html.erb
<center>
<h1>ALL THE BEERS</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Brewer</th>
    <th>Price</th>
    <th>Ounces</th>
    <th>Calories</th>
    <th>Rating</th>
  </tr>

  <% @beers.each do |beer| %>
    <tr>
      <td><%= beer.name %></td>
      <td><%= beer.brewer %></td>
      <td><%= beer.price %></td>
      <td><%= beer.ounce %></td>
      <td><%= beer.calorie %></td>
      <td><%= beer.rating %></td>
      <td><%= link_to 'Show', beer_path(beer) %></td>
      <td><%= link_to 'Edit', edit_beer_path(beer) %></td>
      <td><%= link_to 'Destroy', beer_path(beer),
              method: :delete,
              data: { confirm: 'OK, well, just be careful.' } %></td>
    </tr>
  <% end %>
</table>

<br>
<%= link_to 'GOT A NEW BEER?', new_beer_path %> | <%= link_to "LOG OUT", sessions_destroy_path %>

</center>

app/views/beers/new.html.erb
<center><h1> New beer? </h1></center>

<%= render 'form' %>

<center><%= link_to "BACK", beers_path %>| <%= link_to "LOG OUT", sessions_destroy_path %></center>

app/views/beers/show.html.erb
<center>
<p>
  <strong>Name</strong>
  <%= @beer.name %>
</p>

<p>
  <strong>Brewer</strong>
  <%= @beer.brewer %>
</p>

<p>
  <strong>Price</strong>
  <%= @beer.price %>
</p>

<p>
  <strong>Ounces</strong>
  <%= @beer.ounce %>
</p>

<p>
  <strong>Calories</strong>
  <%= @beer.calorie %>
</p>

<p>
  <strong>Rating</strong>
  <%= @beer.rating %>
</p>
---------------
<br>
<h3> Reviews </h2>
<%= render @beer.reviews %>

<br>
<h3>Add a review?</h3>
<%= render 'reviews/form' %>
</center>
<br>
<br>
<center>
<%= link_to 'GOT A NEW BEER?', new_beer_path %>
 |  <%= link_to 'WANNA CHANGE A BEER?', edit_beer_path %>
 | <%= link_to "LOG OUT", sessions_destroy_path %>
</center>
<br>
<center>
<%= link_to "BACK", beers_path %>
</center>

app/views/dashboards/index.html.erb
<center>
<p>Dashboards#index</p>
<p>Find me in app/views/dashboards/index.html.erb</p>
<br>
<h1> BEERMATH, Y'ALL </h1>
<br>
<%= link_to 'SEE ALL THE BEERS', controller: 'beers' %>
| <%= link_to 'GOT A NEW BEER?', new_beer_path %>
| <%= link_to "LOG OUT", sessions_destroy_path %>
</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Beermath</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p id="notice"><%= notice %></p>

<%= yield %>

</body>
</html>

app/views/reviews/_form.html.erb
<%= form_for([@beer, @beer.reviews.build]) do |f| %>
  <p>
    <%= f.label :commenter %> <br>
    <%= f.text_field :commenter %>
  </p>

  <p>
    <%= f.label :body %> <br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/reviews/_review.html.erb
<p>
  <br>
  <%= review.body %>
  <br>
  <strong> by: <%= review.commenter %></strong>
</p>
<p>
  <%= link_to 'Delete review', [review.beer, review],
              method: :delete,
              data: { confirm: 'You sure?' } %>
</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

| <%= link_to "LOG OUT", sessions_destroy_path %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>
<h1>GOTTA SIGN IN</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <p>
        <%= f.label :email %>
        <%= f.email_field :email %>
      </p>
      <p>
        <%= f.label :password %>
        <%= f.password_field :password %>
      </p>
      <p>
        <%= f.label :password_confirmation, "CONFIRM" %>
        <%= f.password_field :password_confirmation %>
      </p>
      <p>
        <%= f.submit "CREATE", class: "btn btn-primary" %>
      </p>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

| <%= link_to "LOG OUT", sessions_destroy_path %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>

| <%= link_to "LOG OUT", sessions_destroy_path %>